name: Deploy to Vercel

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test & Build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'app/package-lock.json'
      
      - name: Install dependencies
        working-directory: ./app
        run: npm ci
      
      - name: Lint code
        working-directory: ./app
        run: npm run lint || true
      
      - name: Build application
        working-directory: ./app
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
        run: npm run build

  deploy:
    name: Deploy to Vercel
    runs-on: ubuntu-latest
    needs: test
    # Run on push to main/develop OR on pull_request (for PR previews)
    if: (github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')) || github.event_name == 'pull_request'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install Vercel CLI
        run: npm install -g vercel@latest
      
      - name: Deploy to Vercel (Production)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        working-directory: ./app
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: vercel deploy --prod --token=$VERCEL_TOKEN --confirm
      
      - name: Deploy to Vercel (Preview branch)
        if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
        working-directory: ./app
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: vercel deploy --token=$VERCEL_TOKEN --confirm
      
      - name: Deploy to Vercel (PR preview)
        if: github.event_name == 'pull_request'
        working-directory: ./app
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: vercel deploy --token=$VERCEL_TOKEN --confirm
      
      - name: Comment PR with deployment URL
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        with:
          script: |
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: '🚀 Vercel deployment triggered — check the Vercel dashboard or Actions logs for the preview URL.'
            });